// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6797b451cf15bae7, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Id                   uint64   `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6797b451cf15bae7, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *LoginResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6797b451cf15bae7, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6797b451cf15bae7, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "messages.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "messages.user.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "messages.user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "messages.user.LogoutResponse")
}

func init() {
	proto.RegisterFile("messages/user.proto", fileDescriptor_6797b451cf15bae7)
}

var fileDescriptor_6797b451cf15bae7 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x5d, 0x97, 0x75, 0xd8, 0xae, 0x10, 0x45, 0x82, 0x88, 0x2c, 0xf1, 0xd2, 0xd3,
	0xe6, 0xe0, 0x3f, 0xf0, 0xe0, 0x49, 0x2f, 0x39, 0x7a, 0x91, 0x68, 0xc7, 0xa5, 0x48, 0x33, 0x75,
	0x26, 0xc1, 0xbf, 0x2f, 0x4d, 0x53, 0xc1, 0x8b, 0xc7, 0xef, 0x7b, 0xf0, 0xe6, 0x31, 0x70, 0x31,
	0xa0, 0x88, 0x3f, 0xa2, 0xd8, 0x24, 0xc8, 0x87, 0x91, 0x29, 0x92, 0x6a, 0x16, 0x79, 0x98, 0xa4,
	0x79, 0x84, 0xed, 0x13, 0x1d, 0xfb, 0xe0, 0xf0, 0x2b, 0xa1, 0x44, 0x75, 0x0d, 0x9b, 0xc9, 0x07,
	0x3f, 0xa0, 0xae, 0xf6, 0x55, 0x7b, 0xe6, 0x7e, 0x79, 0xca, 0x46, 0x2f, 0xf2, 0x4d, 0xdc, 0xe9,
	0x7a, 0xce, 0x16, 0x36, 0x0c, 0x4d, 0xe9, 0x91, 0x91, 0x82, 0xa0, 0xba, 0x82, 0xb5, 0x44, 0x1f,
	0x93, 0xe4, 0x9a, 0x8d, 0x2b, 0xa4, 0xee, 0xa0, 0x41, 0x66, 0xe2, 0xd7, 0xb2, 0xa3, 0x34, 0x6d,
	0xb3, 0x7c, 0x9e, 0x9d, 0xba, 0x84, 0xd3, 0x48, 0x9f, 0x18, 0xf4, 0x49, 0x0e, 0x67, 0x50, 0x3b,
	0xa8, 0xfb, 0x4e, 0xaf, 0xf6, 0x55, 0xbb, 0x72, 0x75, 0xdf, 0x99, 0xf3, 0x7c, 0x93, 0x52, 0x2c,
	0xe3, 0x4d, 0x0b, 0xbb, 0x45, 0xfc, 0xbf, 0xe2, 0xe1, 0xf6, 0xe5, 0xe6, 0xc3, 0xf3, 0x60, 0x85,
	0xdf, 0x6d, 0xfe, 0x8b, 0xfd, 0xf3, 0xab, 0xb7, 0x75, 0x96, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xe8, 0x8c, 0xe5, 0x43, 0x01, 0x00, 0x00,
}
