// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/delete_device.proto

package delete_device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteDeviceRequest struct {
	DeviceSerial         string   `protobuf:"bytes,1,opt,name=deviceSerial,proto3" json:"deviceSerial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb11bb82bf0208b7, []int{0}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

type DeleteDeviceResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb11bb82bf0208b7, []int{1}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*DeleteDeviceRequest)(nil), "messages.delete_device.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "messages.delete_device.DeleteDeviceResponse")
}

func init() {
	proto.RegisterFile("messages/delete_device.proto", fileDescriptor_fb11bb82bf0208b7)
}

var fileDescriptor_fb11bb82bf0208b7 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0x8d, 0x4f, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x83, 0xc9, 0xea, 0xa1, 0xc8, 0x2a,
	0x59, 0x72, 0x09, 0xbb, 0x80, 0x05, 0x5c, 0xc0, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x25, 0x2e, 0x1e, 0x88, 0x82, 0xe0, 0xd4, 0xa2, 0xcc, 0xc4, 0x1c, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x14, 0x31, 0x25, 0x3d, 0x2e, 0x11, 0x54, 0xad, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x60, 0x5d, 0x1c, 0x41, 0x50,
	0x9e, 0x93, 0x7a, 0x94, 0x6a, 0x5a, 0x62, 0x51, 0xae, 0x7e, 0x71, 0x51, 0xb2, 0x3e, 0xd8, 0x51,
	0xfa, 0xd8, 0x5d, 0x9c, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x05, 0x6a,
	0x1a, 0xb9, 0xd2, 0x00, 0x00, 0x00,
}
