// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/device.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDeviceRequest struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceRequest) Reset()         { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()    {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51214232d75c0e6c, []int{0}
}

func (m *CreateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequest.Unmarshal(m, b)
}
func (m *CreateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequest.Merge(m, src)
}
func (m *CreateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequest.Size(m)
}
func (m *CreateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequest proto.InternalMessageInfo

func (m *CreateDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type CreateDeviceResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceResponse) Reset()         { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()    {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51214232d75c0e6c, []int{1}
}

func (m *CreateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceResponse.Unmarshal(m, b)
}
func (m *CreateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceResponse.Merge(m, src)
}
func (m *CreateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceResponse.Size(m)
}
func (m *CreateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceResponse proto.InternalMessageInfo

func (m *CreateDeviceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateDeviceResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Device struct {
	DeviceSerial         string   `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_51214232d75c0e6c, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDeviceRequest)(nil), "messages.device.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceResponse)(nil), "messages.device.CreateDeviceResponse")
	proto.RegisterType((*Device)(nil), "messages.device.Device")
}

func init() { proto.RegisterFile("messages/device.proto", fileDescriptor_51214232d75c0e6c) }

var fileDescriptor_51214232d75c0e6c = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x46, 0x15, 0x10, 0x11, 0xbd, 0x16, 0x21, 0x99, 0x02, 0x99, 0x20, 0x0a, 0x4b, 0x27, 0x5b,
	0x82, 0x7f, 0x00, 0x88, 0x0d, 0x06, 0x77, 0x63, 0xa9, 0x4c, 0x7b, 0x40, 0x25, 0x1c, 0x87, 0x3b,
	0x97, 0xdf, 0x8f, 0xb8, 0x73, 0x07, 0x32, 0x7e, 0x2f, 0x2f, 0xcf, 0xd2, 0xc1, 0x79, 0x44, 0xe6,
	0xf0, 0x81, 0xec, 0x36, 0xf8, 0xb3, 0x5d, 0xa3, 0x1d, 0x28, 0xe5, 0x64, 0x4e, 0xf7, 0xd8, 0x2a,
	0xee, 0x9e, 0xe0, 0xec, 0x81, 0x30, 0x64, 0x7c, 0x94, 0xed, 0xf1, 0x7b, 0x87, 0x9c, 0x8d, 0x83,
	0x5a, 0x85, 0xa6, 0x6a, 0xab, 0xc5, 0xf4, 0xf6, 0xd2, 0x8e, 0x7e, 0xb4, 0xc5, 0x2f, 0x5a, 0xb7,
	0x84, 0xf9, 0xff, 0x0e, 0x0f, 0xa9, 0x67, 0x34, 0x17, 0x50, 0x73, 0x0e, 0x79, 0xc7, 0x12, 0x3a,
	0xf6, 0x65, 0x99, 0x1b, 0x38, 0x41, 0xa2, 0x44, 0xab, 0xd2, 0x6d, 0x0e, 0xda, 0x6a, 0x31, 0xf1,
	0x33, 0x81, 0xcf, 0xca, 0xba, 0x0d, 0xd4, 0x9a, 0xfb, 0xd3, 0xf5, 0xa1, 0x15, 0x23, 0x6d, 0xc3,
	0x97, 0xd4, 0x26, 0x7e, 0xa6, 0x70, 0x29, 0xcc, 0x5c, 0xc3, 0xb4, 0x48, 0x7d, 0x88, 0xfb, 0x22,
	0x28, 0x7a, 0x09, 0x11, 0xcd, 0x1c, 0x8e, 0x86, 0xcf, 0xd4, 0x63, 0x73, 0x28, 0x9f, 0x74, 0xdc,
	0xb7, 0xaf, 0x57, 0xef, 0x81, 0xa2, 0x63, 0x5a, 0x3b, 0xb9, 0x92, 0x1b, 0xdd, 0xee, 0xad, 0x16,
	0x7c, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x07, 0xe0, 0x15, 0x55, 0x01, 0x00, 0x00,
}
