// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/device_list.proto

package device_list

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeviceListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceListRequest) Reset()         { *m = GetDeviceListRequest{} }
func (m *GetDeviceListRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceListRequest) ProtoMessage()    {}
func (*GetDeviceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_815435cf2efbfaf6, []int{0}
}

func (m *GetDeviceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceListRequest.Unmarshal(m, b)
}
func (m *GetDeviceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceListRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceListRequest.Merge(m, src)
}
func (m *GetDeviceListRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceListRequest.Size(m)
}
func (m *GetDeviceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceListRequest proto.InternalMessageInfo

type GetDeviceListResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDeviceListResponse) Reset()         { *m = GetDeviceListResponse{} }
func (m *GetDeviceListResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceListResponse) ProtoMessage()    {}
func (*GetDeviceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_815435cf2efbfaf6, []int{1}
}

func (m *GetDeviceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceListResponse.Unmarshal(m, b)
}
func (m *GetDeviceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceListResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceListResponse.Merge(m, src)
}
func (m *GetDeviceListResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceListResponse.Size(m)
}
func (m *GetDeviceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceListResponse proto.InternalMessageInfo

func (m *GetDeviceListResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Device struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	FarmId               uint32   `protobuf:"varint,2,opt,name=farmId,proto3" json:"farmId,omitempty"`
	DeviceName           string   `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	DeviceSerial         string   `protobuf:"bytes,4,opt,name=deviceSerial,proto3" json:"deviceSerial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_815435cf2efbfaf6, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Device) GetFarmId() uint32 {
	if m != nil {
		return m.FarmId
	}
	return 0
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDeviceListRequest)(nil), "messages.device_list.GetDeviceListRequest")
	proto.RegisterType((*GetDeviceListResponse)(nil), "messages.device_list.GetDeviceListResponse")
	proto.RegisterType((*Device)(nil), "messages.device_list.Device")
}

func init() {
	proto.RegisterFile("messages/device_list.proto", fileDescriptor_815435cf2efbfaf6)
}

var fileDescriptor_815435cf2efbfaf6 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x8d, 0xcf, 0xc9, 0x2c, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x81, 0xc9, 0xe9, 0x21, 0xc9, 0x29, 0x89, 0x71,
	0x89, 0xb8, 0xa7, 0x96, 0xb8, 0x80, 0x45, 0x7c, 0x32, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x94, 0xfc, 0xb9, 0x44, 0xd1, 0xc4, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xcc,
	0xb8, 0xd8, 0x21, 0xfa, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x64, 0xf4, 0xb0, 0x19,
	0xac, 0x07, 0xd1, 0x1a, 0x04, 0x53, 0xac, 0x54, 0xc5, 0xc5, 0x06, 0x11, 0x12, 0x12, 0xe1, 0x62,
	0x2d, 0xc8, 0xc8, 0xcf, 0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xc4,
	0xb8, 0xd8, 0xd2, 0x12, 0x8b, 0x72, 0x3d, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0xa0,
	0x3c, 0x21, 0x39, 0x2e, 0x2e, 0x88, 0x11, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x60, 0x2d, 0x48,
	0x22, 0x42, 0x4a, 0x5c, 0x3c, 0x10, 0x5e, 0x70, 0x6a, 0x51, 0x66, 0x62, 0x8e, 0x04, 0x0b, 0x58,
	0x05, 0x8a, 0x98, 0x93, 0x6a, 0x94, 0x32, 0xc8, 0x34, 0xfd, 0xe2, 0xa2, 0x64, 0x7d, 0x70, 0x60,
	0xe8, 0x63, 0x0b, 0xa7, 0x24, 0x36, 0xb0, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xbc,
	0xae, 0x51, 0x46, 0x01, 0x00, 0x00,
}
