// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/device_log.proto

package device_log

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeviceLogRequest struct {
	DeviceSerial         string               `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	BeginTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDeviceLogRequest) Reset()         { *m = GetDeviceLogRequest{} }
func (m *GetDeviceLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogRequest) ProtoMessage()    {}
func (*GetDeviceLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4bcc8054c7dd843, []int{0}
}

func (m *GetDeviceLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogRequest.Unmarshal(m, b)
}
func (m *GetDeviceLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogRequest.Merge(m, src)
}
func (m *GetDeviceLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogRequest.Size(m)
}
func (m *GetDeviceLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogRequest proto.InternalMessageInfo

func (m *GetDeviceLogRequest) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *GetDeviceLogRequest) GetBeginTime() *timestamp.Timestamp {
	if m != nil {
		return m.BeginTime
	}
	return nil
}

func (m *GetDeviceLogRequest) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type GetDeviceLogResponse struct {
	DeviceLog            []*DeviceLog `protobuf:"bytes,1,rep,name=device_log,json=deviceLog,proto3" json:"device_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDeviceLogResponse) Reset()         { *m = GetDeviceLogResponse{} }
func (m *GetDeviceLogResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogResponse) ProtoMessage()    {}
func (*GetDeviceLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4bcc8054c7dd843, []int{1}
}

func (m *GetDeviceLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogResponse.Unmarshal(m, b)
}
func (m *GetDeviceLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogResponse.Merge(m, src)
}
func (m *GetDeviceLogResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogResponse.Size(m)
}
func (m *GetDeviceLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogResponse proto.InternalMessageInfo

func (m *GetDeviceLogResponse) GetDeviceLog() []*DeviceLog {
	if m != nil {
		return m.DeviceLog
	}
	return nil
}

type DeviceLog struct {
	DeviceSerial         string               `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	Datetime             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Humidity             int32                `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Temp                 int32                `protobuf:"varint,4,opt,name=temp,proto3" json:"temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeviceLog) Reset()         { *m = DeviceLog{} }
func (m *DeviceLog) String() string { return proto.CompactTextString(m) }
func (*DeviceLog) ProtoMessage()    {}
func (*DeviceLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4bcc8054c7dd843, []int{2}
}

func (m *DeviceLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceLog.Unmarshal(m, b)
}
func (m *DeviceLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceLog.Marshal(b, m, deterministic)
}
func (m *DeviceLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceLog.Merge(m, src)
}
func (m *DeviceLog) XXX_Size() int {
	return xxx_messageInfo_DeviceLog.Size(m)
}
func (m *DeviceLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceLog.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceLog proto.InternalMessageInfo

func (m *DeviceLog) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *DeviceLog) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *DeviceLog) GetHumidity() int32 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *DeviceLog) GetTemp() int32 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func init() {
	proto.RegisterType((*GetDeviceLogRequest)(nil), "messages.device_log.GetDeviceLogRequest")
	proto.RegisterType((*GetDeviceLogResponse)(nil), "messages.device_log.GetDeviceLogResponse")
	proto.RegisterType((*DeviceLog)(nil), "messages.device_log.DeviceLog")
}

func init() {
	proto.RegisterFile("messages/device_log.proto", fileDescriptor_e4bcc8054c7dd843)
}

var fileDescriptor_e4bcc8054c7dd843 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x95, 0xbf, 0xf6, 0x83, 0xe6, 0x0a, 0x8b, 0xcb, 0x10, 0x32, 0x40, 0x14, 0x18, 0x32, 0x39,
	0x52, 0x11, 0x48, 0x0c, 0x2c, 0x08, 0x89, 0x85, 0x29, 0xc0, 0xc2, 0x52, 0x25, 0xf5, 0xd5, 0x58,
	0x8a, 0xe3, 0x10, 0x3b, 0x48, 0xfc, 0x13, 0x7e, 0x04, 0x3f, 0x12, 0xc5, 0x21, 0x89, 0x90, 0x2a,
	0xd1, 0xed, 0xee, 0xde, 0x7b, 0xf7, 0xfc, 0x6c, 0xc3, 0xb1, 0x42, 0x63, 0x32, 0x81, 0x26, 0xe1,
	0xf8, 0x2e, 0xd7, 0xb8, 0x2a, 0xb4, 0x60, 0x55, 0xad, 0xad, 0xa6, 0x8b, 0x1e, 0x62, 0x23, 0x14,
	0x9c, 0x0a, 0xad, 0x45, 0x81, 0x89, 0xa3, 0xe4, 0xcd, 0x26, 0xb1, 0x52, 0xa1, 0xb1, 0x99, 0xaa,
	0x3a, 0x55, 0xf4, 0x45, 0x60, 0x71, 0x8f, 0xf6, 0xce, 0x49, 0x1e, 0xb4, 0x48, 0xf1, 0xad, 0x41,
	0x63, 0xe9, 0x19, 0x1c, 0xfe, 0xac, 0x31, 0x58, 0xcb, 0xac, 0xf0, 0x49, 0x48, 0x62, 0x2f, 0x3d,
	0xe8, 0x86, 0x8f, 0x6e, 0x46, 0xaf, 0x01, 0x72, 0x14, 0xb2, 0x5c, 0xb5, 0x5b, 0xfd, 0x7f, 0x21,
	0x89, 0xe7, 0xcb, 0x80, 0x75, 0x96, 0xac, 0xb7, 0x64, 0x4f, 0xbd, 0x65, 0xea, 0x39, 0x76, 0xdb,
	0xd3, 0x4b, 0x98, 0x61, 0xc9, 0x3b, 0xe1, 0xe4, 0x4f, 0xe1, 0x3e, 0x96, 0xbc, 0xed, 0xa2, 0x67,
	0x38, 0xfa, 0x7d, 0x5a, 0x53, 0xe9, 0xd2, 0x20, 0xbd, 0x01, 0x18, 0x53, 0xfb, 0x24, 0x9c, 0xc4,
	0xf3, 0xe5, 0x09, 0xdb, 0x72, 0x23, 0x6c, 0xd4, 0x7a, 0xbc, 0x2f, 0xa3, 0x4f, 0x02, 0xde, 0x00,
	0xec, 0x96, 0xfd, 0x0a, 0x66, 0x3c, 0xb3, 0xb8, 0x63, 0xf2, 0x81, 0x4b, 0x03, 0x98, 0xbd, 0x36,
	0x4a, 0x72, 0x69, 0x3f, 0x5c, 0xf0, 0xff, 0xe9, 0xd0, 0x53, 0x0a, 0x53, 0x8b, 0xaa, 0xf2, 0xa7,
	0x6e, 0xee, 0xea, 0xdb, 0xf3, 0x97, 0x68, 0x93, 0xd5, 0x2a, 0x31, 0xf5, 0xba, 0x7b, 0xc5, 0x64,
	0xcb, 0x17, 0xc8, 0xf7, 0x1c, 0x74, 0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xc1, 0x36, 0xb6,
	0x20, 0x02, 0x00, 0x00,
}
